/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koznaznajava;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author WIN 10
 */
public class AddQuestionWindow extends javax.swing.JFrame {
    int sentFrom;
    /**
     * Creates new form AddQuestionWindow
     */
    String suggestedQuestion;
    String suggestedCorrectAnswer;
    String suggestedFalseAnswer1;
    String suggestedFalseAnswer2;
    String suggestedFalseAnswer3;
    String userName;
    
    public AddQuestionWindow() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorrectAnswer = new javax.swing.JTextField();
        jTextFieldFalseAnswer1 = new javax.swing.JTextField();
        jTextFieldFalseAnswer2 = new javax.swing.JTextField();
        jTextFieldFalseAnswer3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSuggestedQuestion = new javax.swing.JTextArea();
        jButtonSubmitSuggestion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Унесите текст питања:");

        jLabel2.setText("Унесите тачан одговор на питање:");

        jLabel3.setText("Унесите први нетачан одговор на питање:");

        jLabel4.setText("Унесите други нетачан одговор на питање:");

        jLabel5.setText("Унесите трећи нетачан одговор на питање:");

        jTextFieldFalseAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFalseAnswer3ActionPerformed(evt);
            }
        });

        jTextAreaSuggestedQuestion.setColumns(20);
        jTextAreaSuggestedQuestion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSuggestedQuestion);

        jButtonSubmitSuggestion.setText("Потврди");
        jButtonSubmitSuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitSuggestionActionPerformed(evt);
            }
        });
        jButtonSubmitSuggestion.setFocusPainted(false);

        jLabel6.setText("Унесите своје име:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFalseAnswer2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(jTextFieldFalseAnswer3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFalseAnswer1)
                            .addComponent(jTextFieldCorrectAnswer)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSubmitSuggestion)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFalseAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFalseAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFalseAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonSubmitSuggestion)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFalseAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFalseAnswer3ActionPerformed
      
    }//GEN-LAST:event_jTextFieldFalseAnswer3ActionPerformed

    private void jButtonSubmitSuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitSuggestionActionPerformed
        if(!jTextAreaSuggestedQuestion.getText().isBlank()){
            if(!jTextFieldCorrectAnswer.getText().isBlank()){
                if(jTextFieldFalseAnswer1.getText().isBlank() || jTextFieldFalseAnswer2.getText().isBlank() || jTextFieldFalseAnswer3.getText().isBlank()){
                    JOptionPane.showMessageDialog(this, "Нисте унели довољно нетачних одговора на предложено питање!", "", JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                        Connection c = DriverManager.getConnection(KoZnaZnaJava.QUESTIONS_DATABASE_URL);
                        Statement s = c.createStatement();
                        /**/
                        suggestedQuestion = jTextAreaSuggestedQuestion.getText();
                        suggestedCorrectAnswer = jTextFieldCorrectAnswer.getText();
                        suggestedFalseAnswer1 = jTextFieldFalseAnswer1.getText();
                        suggestedFalseAnswer2 = jTextFieldFalseAnswer2.getText();
                        suggestedFalseAnswer3 = jTextFieldFalseAnswer3.getText();
                        userName = jTextFieldUserName.getText();
                        
                        s.executeUpdate("INSERT INTO SuggestedQuestionsByUsers (SuggestedQuestion, CorrectAnswer, FalseAnswer1, FalseAnswer2, FalseAnswer3, SuggestedBy)"
                                + "VALUES ('" + suggestedQuestion + "', '" + suggestedCorrectAnswer + "', '"+ suggestedFalseAnswer1 + "', '"+suggestedFalseAnswer2+"', '" + suggestedFalseAnswer3 +"', '"+ userName +"')");
                        
                        JOptionPane.showMessageDialog(this, "Питање је забележено и администратори ће размотрити додавање питања у игру!", "Потврда уноса", JOptionPane.INFORMATION_MESSAGE);
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(AddQuestionWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Нисте унели тачан одговор на предложено питање!", "", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Нисте унели предложено питање!", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitSuggestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmitSuggestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSuggestedQuestion;
    private javax.swing.JTextField jTextFieldCorrectAnswer;
    private javax.swing.JTextField jTextFieldFalseAnswer1;
    private javax.swing.JTextField jTextFieldFalseAnswer2;
    private javax.swing.JTextField jTextFieldFalseAnswer3;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
