/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koznaznajava;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WIN 10
 */
public class EndWindow extends javax.swing.JFrame {

    String playerName;
    int score;
    int wrongAnswerScore;
    int points;
    
    
    boolean resultSentToDatabase;
    
    public EndWindow() {
        
        initComponents();
        
        System.out.println("default constructor is called");
    }
    
    public EndWindow(int score, int wrongAnswerScore) {
        initComponents();
        
        resultSentToDatabase = false;
        
        this.score = score;
        this.wrongAnswerScore = wrongAnswerScore;
        this.playerName = null;
        
        this.points = score*10 - wrongAnswerScore * 5;
        
        jLabelScore.setText("Број тачних одговора: " + Integer.toString(this.score));
        jLabelWrongAnswersScore.setText("Број нетачних одговора: " + Integer.toString(this.wrongAnswerScore));
        jLabelPoints.setText("Укупан број бодова: " + Integer.toString(points));
        
        this.populate();
    }

/**
     * Creates new form EndWindow
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabelPoints = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSendResult = new javax.swing.JButton();
        jTextFieldPlayerName = new javax.swing.JTextField();
        jLabelWrongAnswersScore = new javax.swing.JLabel();
        jButtonRestart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Крај игре");

        jLabelScore.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelScore.setText("jLabelScore");

        jLabelPoints.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelPoints.setText("jLabelPoints");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Забележи резултат");

        jLabel3.setText("Име:");

        jButtonSendResult.setText("Пошаљи резултат");
        jButtonSendResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSendResult)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButtonSendResult)
                .addGap(127, 127, 127))
        );

        jLabelWrongAnswersScore.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabelWrongAnswersScore.setText("jLabelWrongAnswersScore");

        jButtonRestart.setText("Играј поново");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Предложи питање");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabelWrongAnswersScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonRestart)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelScore)
                        .addGap(61, 61, 61)
                        .addComponent(jLabelWrongAnswersScore)
                        .addGap(56, 56, 56)
                        .addComponent(jLabelPoints)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRestart)
                    .addComponent(jButton1))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendResultActionPerformed
        if(!resultSentToDatabase){
            java.util.Date date=new java.util.Date();  
            String dateString = date.toString();
            //System.out.println(date);

            
            
            if(!jTextFieldPlayerName.getText().isEmpty()){
                playerName = jTextFieldPlayerName.getText();

                try {
                    Connection c = DriverManager.getConnection(KoZnaZnaJava.RESULTS_DATABASE_URL);
                    Statement s = c.createStatement();
                    //s.executeUpdate("INSERT INTO Results (PlayerName, CorrectAnswers, Points) VALUES ('" + playerName + "', " + score + ", " + points + ");"); //OVO RADI
                    s.executeUpdate("INSERT INTO Results (PlayerName, CorrectAnswers, Points, DatePlayed) VALUES ('" + playerName + "', " + score + ", " + points + ", '" + dateString + "');");

                    JOptionPane.showMessageDialog(this, "Резултат је забележен", "Потврда уноса", JOptionPane.INFORMATION_MESSAGE);
                    resultSentToDatabase = true;
                    
                    this.populate();
                }catch(SQLException ex){
                    Logger.getLogger(EndWindow.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else{
                System.out.println("aaaa");
                JOptionPane.showMessageDialog(this, "Морате уписати име како би се резултат забележио!", "Погрешан унос", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Резултат је већ забележен!", "Недозвољен унос", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSendResultActionPerformed

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        this.dispose();
        
        StartingWindow sw = new StartingWindow();
        sw.setLocation(200, 100);
        sw.setVisible(true);
    }//GEN-LAST:event_jButtonRestartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddQuestionWindow aqw = new AddQuestionWindow();
        aqw.setLocation(400, 300);
        aqw.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JButton jButtonSendResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPoints;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelWrongAnswersScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPlayerName;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        try {
            Connection c = DriverManager.getConnection(KoZnaZnaJava.RESULTS_DATABASE_URL);
            Statement s = c.createStatement();
            
            ResultSet rs = s.executeQuery("SELECT * FROM Results");
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("PlayerName");
            dtm.addColumn("CorrectAnswers"); //srpski todo
            dtm.addColumn("Points");
            dtm.addColumn("DatePlayed"); 
            while(rs.next()){
                Object[] tableRow = new Object[5];
                tableRow[0] = rs.getInt("ID");
                tableRow[1] = rs.getString("PlayerName");
                tableRow[2] = rs.getInt("CorrectAnswers");
                tableRow[3] = rs.getInt("Points");
                tableRow[4] = rs.getString("DatePlayed");
                dtm.addRow(tableRow);
                
            }
            //jTable1.setAutoCreateRowSorter(true);
            
            jTable1.setModel(dtm);
                    
                    
                    
        } catch (SQLException ex) {
            Logger.getLogger(EndWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
